services:
  backend:
    build:
      context: ./heart-pilot-backend
      dockerfile: Dockerfile.deploy
    environment:
      SPRING_PROFILES_ACTIVE: prod
  frontend:
    build:
      context: ./heart-pilot-frontend
      dockerfile: Dockerfile.deploy
