services:
  backend:
    build:
      context: ./heart-pilot-backend
      dockerfile: Dockerfile.deploy
  frontend:
    build:
      context: ./heart-pilot-frontend
      dockerfile: Dockerfile.deploy
